
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: secure_docs_db
      POSTGRES_USER: secure_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - secure-net

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - SECRET_KEY=prod_secret_key_change_me_in_prod
      - ALLOWED_HOSTS=localhost,backend,127.0.0.1
      - DB_NAME=secure_docs_db
      - DB_USER=secure_user
      - DB_PASSWORD=secure_password
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - ENCRYPTION_KEY=Z6GP5c16rd6y92CWCgg6SUltLZrI7M_DTWiLRRGa5Ac=
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      # In prod, we would use a real email backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - secure-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}

    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - secure-net


volumes:
  postgres_data:
  media_volume:

networks:
  secure-net:
    driver: bridge
